# Generated by Django 5.2.7 on 2025-12-02 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_emailverification'),
        ('accounts', '0006_change_profile_picture'),
    ]

    operations = [
    ]
