# Generated by Django 5.0.7 on 2025-10-31 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('food', 'Food & Beverages'), ('books', 'Books'), ('home', 'Home & Garden'), ('sports', 'Sports & Outdoors'), ('health', 'Health & Beauty'), ('other', 'Other')], default='other', max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_of_measure', models.CharField(choices=[('pieces', 'Pieces'), ('packs', 'Packs'), ('boxes', 'Boxes'), ('kilograms', 'Kilograms'), ('grams', 'Grams'), ('liters', 'Liters'), ('meters', 'Meters'), ('units', 'Units'), ('pairs', 'Pairs'), ('sets', 'Sets'), ('bottles', 'Bottles'), ('cartons', 'Cartons'), ('bags', 'Bags')], default='pieces', max_length=20)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
        ),
    ]
