# Generated by Django 5.2.7 on 2025-12-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_change_image_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_content_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
