# Generated by Django 5.2.8 on 2025-11-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, help_text='JSON object storing staff permissions'),
        ),
    ]
